
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programleftPLUSMINUSleftTIMESDIVIDErightUMINUSASSIGN DIVIDE ELSE GREATERTHAN ID IF LBRACE LESSTHAN LPAREN MINUS NUMBER PLUS RBRACE RPAREN SEMICOLON THEN TIMESprogram : program statementprogram : statementstatement : ID ASSIGN expression SEMICOLONexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expression\n                  | expression GREATERTHAN expression\n                  | expression LESSTHAN expressionexpression : MINUS expression %prec UMINUSexpression : NUMBERexpression : IDstatement : IF LPAREN expression RPAREN LBRACE statements RBRACE ELSE LBRACE statements RBRACEstatements : statements statementstatements : statement'
    
_lr_action_items = {'ID':([0,1,2,5,6,7,10,13,14,15,16,17,18,19,28,29,30,32,34,35,36,],[3,3,-2,-1,8,8,8,-3,8,8,8,8,8,8,3,3,-15,-14,3,3,-13,]),'IF':([0,1,2,5,13,28,29,30,32,34,35,36,],[4,4,-2,-1,-3,4,4,-15,-14,4,4,-13,]),'$end':([1,2,5,13,36,],[0,-2,-1,-3,-13,]),'ASSIGN':([3,],[6,]),'LPAREN':([4,],[7,]),'MINUS':([6,7,8,9,10,11,12,14,15,16,17,18,19,20,22,23,24,25,26,27,],[10,10,-12,15,10,-11,15,10,10,10,10,10,10,-10,-4,-5,-6,-7,15,15,]),'NUMBER':([6,7,10,14,15,16,17,18,19,],[11,11,11,11,11,11,11,11,11,]),'SEMICOLON':([8,9,11,20,22,23,24,25,26,27,],[-12,13,-11,-10,-4,-5,-6,-7,-8,-9,]),'PLUS':([8,9,11,12,20,22,23,24,25,26,27,],[-12,14,-11,14,-10,-4,-5,-6,-7,14,14,]),'TIMES':([8,9,11,12,20,22,23,24,25,26,27,],[-12,16,-11,16,-10,16,16,-6,-7,16,16,]),'DIVIDE':([8,9,11,12,20,22,23,24,25,26,27,],[-12,17,-11,17,-10,17,17,-6,-7,17,17,]),'GREATERTHAN':([8,9,11,12,20,22,23,24,25,26,27,],[-12,18,-11,18,-10,-4,-5,-6,-7,18,18,]),'LESSTHAN':([8,9,11,12,20,22,23,24,25,26,27,],[-12,19,-11,19,-10,-4,-5,-6,-7,19,19,]),'RPAREN':([8,11,12,20,22,23,24,25,26,27,],[-12,-11,21,-10,-4,-5,-6,-7,-8,-9,]),'RBRACE':([13,29,30,32,35,36,],[-3,31,-15,-14,36,-13,]),'LBRACE':([21,33,],[28,34,]),'ELSE':([31,],[33,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([0,1,28,29,34,35,],[2,5,30,32,30,32,]),'expression':([6,7,10,14,15,16,17,18,19,],[9,12,20,22,23,24,25,26,27,]),'statements':([28,34,],[29,35,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> program statement','program',2,'p_program_multiple','parser.py',16),
  ('program -> statement','program',1,'p_program_single','parser.py',20),
  ('statement -> ID ASSIGN expression SEMICOLON','statement',4,'p_statement_assign','parser.py',24),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','parser.py',28),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','parser.py',29),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','parser.py',30),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','parser.py',31),
  ('expression -> expression GREATERTHAN expression','expression',3,'p_expression_binop','parser.py',32),
  ('expression -> expression LESSTHAN expression','expression',3,'p_expression_binop','parser.py',33),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','parser.py',43),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',47),
  ('expression -> ID','expression',1,'p_expression_id','parser.py',51),
  ('statement -> IF LPAREN expression RPAREN LBRACE statements RBRACE ELSE LBRACE statements RBRACE','statement',11,'p_statement_if','parser.py',55),
  ('statements -> statements statement','statements',2,'p_statements_multiple','parser.py',59),
  ('statements -> statement','statements',1,'p_statements_single','parser.py',63),
]
